return {
  { "folke/flash.nvim", enabled = false },
  { "nvim-telescope/telescope.nvim", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "mini.indentscope", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "toggleterm.nvim", enabled = false },
}
